### ISSUE TITLE
Make all utterances simpler

### ISSUE THREAD

**Issue by meeshyep** [ChoreMatick/ChoreMatick#62]

**Comment by DagmaraSz** [comment]
have a keyword that triggers every response so that alexa isn't confused

**Comment by DagmaraSz** [comment]
getChoreIntent (What's/what is) my (chore/task) for {choreDate}? -> make today the default date.

**Comment by DagmaraSz** [comment]
getDoneResponse (I've/I have/I'm/I am) (done/finished) {chore} for {date} -> default first chore for the day

**Comment by DagmaraSz** [comment]
addChoreIntent (Add/Create) a (chore/task) {date} -> by default for today

**Comment by DagmaraSz** [comment]
ConfirmIntent Confirm {password}

**Comment by DagmaraSz** [comment]
GetCompletedIntent How many chores (were/are/have been)  (completed/finished/done)
GetCompletedIntent Total (number of) chores that (were/are/have been) (completed/finished/done)

**Comment by DagmaraSz** [comment]
GetListChores (Tell me/Give me) a list of chores
